spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinebh
    username: cinebh_app
    password: cinebh123
  jpa:
    show-sql: true
  mail:
    host: mail.smtp2go.com
    port: 2525
    username: "atlantbhpraksa"
    password: ${smtp2go.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  storage:
    bucket: cinebh
    region: eu-central-1
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    public-base-url: http://localhost:9000/cinebh
    path-style-access-enabled: true
  notification:
    from-address: "slavisa.covakusic@student.etf.unibl.org"
    from-name: "Cinebh"
    verification-code-ttl-minutes: 15

