spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinebh
    username: cinebh_app
    password: cinebh123
  jpa:
    show-sql: true

app:
  storage:
    bucket: cinebh
    region: eu-central-1
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    public-base-url: http://localhost:9000/cinebh
    path-style-access-enabled: true
