spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinebh
    username: cinebh_app
    password: cinebh123
  jpa:
    show-sql: true
  mail:
    host: mail.smtp2go.com
    port: 2525
    username: "atlantbhpraksa"
    password: ${smtp2go.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  storage:
    bucket: cinebh
    region: eu-central-1
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    public-base-url: http://localhost:9000/cinebh
    path-style-access-enabled: true
  notification:
    from-address: "slavisa.covakusic@student.etf.unibl.org"
    from-name: "Cinebh"
  verification:
    code-ttl-minutes: 15
    code-length: 6
  validation:
    cache:
      mx-record-ttl-days: 7
      mx-record-prefix: "mx_record:"
  security:
    jwt:
      secret: "v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdTgUkXp2s5v8y/B?E(G+KbPeShVmYq"
      access-token-expiration-ms: 900000
      refresh-token-expiration-ms: 604800000
    cookie:
      domain: "localhost"
      secure: true
      http-only: true
      same-site: "None"
    cors:
      allowed-origins:
        - "https://localhost:5173"
        - "http://localhost:5173"
      allowed-methods: [ "GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS" ]
      allowed-headers: [ "Authorization", "Content-Type", "X-Requested-With", "Accept" ]
      exposed-headers: [ "Set-Cookie" ]
