Enum UserRole {
  CUSTOMER
  EMPLOYEE
  ADMIN
}

Enum MovieStatus {
  DRAFT
  PUBLISHED
  ARCHIVED
}

Enum SeatType {
  REGULAR
  LOVE
  VIP
}

Enum ReservationStatus {
  PENDING
  COMPLETED
  CANCELLED
  EXPIRED
}

Table users {
  id uuid [primary key]
  first_name varchar(50) [not null]
  last_name varchar(50) [not null]
  email varchar(255) [unique, not null]
  password_hash varchar(255) [not null]
  phone varchar(50) [unique, not null]
  profile_image_url varchar(255) [not null]
  role UserRole [default: 'CUSTOMER']
  is_active boolean [default: false]
  city_id uuid [not null]
  street_address varchar(50) [not null]
  created_at timestamp [default: `now()`]
  updated_at timestamp
}

Table password_reset_codes {
  id uuid [primary key]
  user_id uuid [not null]
  code varchar(6) [not null]
  expires_at timestamp [not null]
  is_used boolean [default: false]
  created_at timestamp [default: `now()`]
}

Table movies {
  id uuid [primary key]
  title varchar(255) [not null]
  synopsis text
  duration_minutes integer
  pg_rating varchar(8)
  language varchar(50)
  director varchar(255)
  trailer_url varchar(255)
  cover_image_url varchar(255)
  status MovieStatus [default: 'DRAFT']
  draft_step integer [default: 1]
  release_date date
  end_date date
  created_at timestamp [default: `now()`]
}

Table genres {
  id uuid [primary key]
  name varchar(50) [unique, not null]
}

Table movie_genres {
  id uuid [primary key]
  movie_id uuid [not null]
  genre_id uuid [not null]
  Indexes {
    (movie_id, genre_id) [unique]
  }
}

Table people {
  id uuid [primary key]
  first_name varchar(100) [not null]
  last_name varchar(100) [not null]
}

Table movie_cast {
  id uuid [primary key]
  movie_id uuid [not null]
  person_id uuid [not null]
  character_name varchar(100)
  Indexes {
    (movie_id, person_id) [unique]
  }
}

Table movie_writers {
  id uuid [primary key]
  movie_id uuid [not null]
  person_id uuid [not null]
  Indexes {
    (movie_id, person_id) [unique]
  }
}

Table movie_images {
  id uuid [primary key]
  movie_id uuid [not null]
  image_url varchar(255) [not null]
}

Table cities {
  id uuid [primary key]
  name varchar(100) [not null]
  country varchar(100) [default: 'Bosnia and Herzegovina']
}

Table venues {
  id uuid [primary key]
  city_id uuid [not null]
  name varchar(255) [not null]
  street_address varchar(255) [not null]
  phone varchar(50)
  image_url varchar(255)
}

Table halls {
  id uuid [primary key]
  venue_id uuid [not null]
  name varchar(50) [not null]
}

Table seats {
  id uuid [primary key]
  hall_id uuid [not null]
  row_num varchar(10) [not null]
  seat_num varchar(10) [not null]
  type SeatType [default: 'REGULAR']
  price decimal [not null]
}

Table projections {
  id uuid [primary key]
  movie_id uuid [not null]
  hall_id uuid [not null]
  start_time timestamp [not null]
  created_at timestamp [default: `now()`]
  Indexes {
    (hall_id, start_time) [unique]
  }
}

Table reservations {
  id uuid [primary key]
  user_id uuid [not null]
  projection_id uuid [not null]
  status ReservationStatus [default: 'PENDING']
  total_price decimal [not null]
  expires_at timestamp [not null]
  is_reminder_enabled boolean [default: false]
  created_at timestamp [default: `now()`]
}

Table reservation_seats {
  id uuid [primary key]
  reservation_id uuid [not null]
  seat_id uuid [not null]
  projection_id uuid [not null]
  Indexes {
    (reservation_id, seat_id) [unique]
    (projection_id, seat_id) [unique]
  }
}

Table notifications {
  id uuid [primary key]
  user_id uuid [not null]
  title varchar(255) [not null]
  message text [not null]
  is_read boolean [default: false]
  send_time timestamp
  created_at timestamp [default: `now()`]
}

Ref: users.city_id > cities.id
Ref: password_reset_codes.user_id > users.id

Ref: movie_genres.movie_id > movies.id
Ref: movie_genres.genre_id > genres.id

Ref: movie_cast.movie_id > movies.id
Ref: movie_cast.person_id > people.id

Ref: movie_writers.movie_id > movies.id
Ref: movie_writers.person_id > people.id

Ref: movie_images.movie_id > movies.id

Ref: venues.city_id > cities.id
Ref: halls.venue_id > venues.id
Ref: seats.hall_id > halls.id

Ref: projections.movie_id > movies.id
Ref: projections.hall_id > halls.id

Ref: reservations.user_id > users.id
Ref: reservations.projection_id > projections.id

Ref: reservation_seats.reservation_id > reservations.id
Ref: reservation_seats.seat_id > seats.id
Ref: reservation_seats.projection_id > projections.id

Ref: notifications.user_id > users.id
